<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PDDGBC5" failures="1" tests="7" name="test.LoginPageTest" time="271.043" errors="0" timestamp="2024-07-02T16:07:58 IST" skipped="3">
  <testcase classname="test.LoginPageTest" name="verifyUserLoginwithValidCredentials" time="30.797">
    <skipped/>
  </testcase> <!-- verifyUserLoginwithValidCredentials -->
  <testcase classname="test.LoginPageTest" name="verifyUserLoginwithValidCredentials" time="40.243">
    <failure message="Invalid user expected [Welcome XYZ,] but found [Welcome admin,]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Invalid user expected [Welcome XYZ,] but found [Welcome admin,]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at test.LoginPageTest.verifyUserLoginwithValidCredentials(LoginPageTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyUserLoginwithValidCredentials -->
  <testcase classname="test.LoginPageTest" name="verifErrorMessageWhileUserLoginwithInvalidCredentials" time="24.202"/>
  <testcase classname="test.LoginPageTest" name="verifErrorMessageWhileUserLoginwithInvalidCredentials" time="32.160"/>
  <testcase classname="test.LoginPageTest" name="verifyUserLoginwithValidCredentials" time="34.511">
    <skipped/>
  </testcase> <!-- verifyUserLoginwithValidCredentials -->
  <testcase classname="test.LoginPageTest" name="verifErrorMessageWhileUserLoginwithInvalidCredentials" time="36.851"/>
  <testcase classname="test.LoginPageTest" name="verifyUserLoginwithValidCredentials" time="72.279">
    <skipped/>
  </testcase> <!-- verifyUserLoginwithValidCredentials -->
</testsuite> <!-- test.LoginPageTest -->
